apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-rs
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: hashicorp/http-echo
        ports:
        - containerPort: 5678
        args: ["Hello from API"]
